FerrumTokenList.json
**Summary**
- added rvf mumbai tokens with chain id 8001
- added paid mumbai and rinkeby tokens
=> Added mumbai tokens

FerrumTokenList.json
**Summary**
- added puerfi testnet on mumbai, bsctestnet and rinkeby
=> added purefi testnet details

FerrumTokenList.json
=> correct purefi

FerrumTokenList.json
**Summary**
- replaced UFI main-net images with transparent images
=> UFI main-net transparent images

FerrumTokenList.json
**Summary**
- Adds spores network tokens to tokens list for bsc-testnet and rinkeby
=> Added spores network tokens to list

FerrumTokenList.json
**Summary**
- added defit test tokens to json
=> added defit test tokens

FerrumTokenList.json
**summary**
- replaced the defit image with the transprent alternative
- added purefi  mumbai_testnet image
=> Replace Defit image with transparent bkg

FerrumTokenList.json
**Summary**
- Added rvf bsctestnet object item
=> added BSC-testnet RVF

FerrumTokenList.json
- adds signata staging config for rinkeby and bsc-testnet
=> Added signata staging

FerrumTokenList.json
- adds signata config on bsctest and rinkeby
- adds ispolink config on bsctest and rinkeby
=> Signata staging

FerrumTokenList.json
1. Added CRYSTL.Finance demo token data
=> Added CRYSTL.Finance test token data

FerrumTokenList.json
1. Fixed contract address for Crystl Rinkeby and BSC
=> Fixed contract address for Crystl Rinkeby and BSC

FerrumTokenList.json
1. Updated bloxmove token logo
=> Updated bloxmove token logo

FerrumTokenList.json
1. adding XLD mainnet tokens to tokenlist
=> adding XLD mainnet tokens to tokenlist

FerrumTokenList.json
1. Added ispolink mainnet tokens
=> Added ispolink mainnet tokens

FerrumTokenList.json
=> Adding TRL Mainnet tokens

FerrumTokenList.json
1. Added Ahmed Ferrum token to rinkeby and avax testnet
=> Added Ahmed Ferrum token to rinkeby and avax testnet

FerrumTokenList.json
1. Updated addresses of Ahmed Ferrum token
=> Updated addresses of Ahmed Ferrum token

FerrumTokenList.json
=> Updated SDAO token

FerrumTokenList.json
1. Added bloxmove hackathon token
=> Added bloxmove hackathon token

FerrumTokenList.json
=> Added shoe token logo

FerrumTokenList.json
1. Added SDAO and SHOEFY tokens
=> Added SDAO and SHOEFY tokens

FerrumTokenList.json
=> Added PureFi Polygon Token

FerrumTokenList.json
1. Added Yarloo to BSC and Polygon Testnets
=> Added Yarloo to BSC and Polygon Testnets

FerrumTokenList.json
1. Fixed yarl mumbai testnet contract
=> Fixed yarl mumbai testnet contract

NetworkLogos.json
1. Fixed JSON formatting errors
=> Fixed JSON formatting errors

NetworkLogos.json
1. Fixed more json formatting errors
=> Fixed more json formatting errors

FerrumTokenList.json
1. added AFRM on Moonriver mainnet
=> added AFRM on Moonriver mainnet

FerrumTokenList.json
**what does this Pr do?**
- fixes issue with paid bsc token
=> Added paid token

FerrumTokenList.json
- Adds cfrm on bsc and arbitrum
=> [Feat]: cfrm tokens on bsc and arbitrum

FerrumTokenList.json
- Changes the RVF v1 token to v2
=> Rvf ethereum v2

FerrumTokenList.json
- Adds new logo for RVF token.
=> Fix:  Added new rvf token logo

FerrumTokenList.json
=> removed paid from list
